backend: pytorch

dataset: cms
sort_data: yes
data_dir:
gpus: 1
gpu_batch_multiplier: 1
load:
num_epochs: 10
patience: 20
lr: 0.0005
lr_schedule: cosinedecay  # constant, cosinedecay, onecycle
conv_type: gnn_lsh
ntrain:
ntest:
nvalid:
num_workers: 0
prefetch_factor:
checkpoint_freq:
comet_name: particleflow-pt
comet_offline: False
comet_step_freq: 10
dtype: bfloat16

model:
  input_encoding: joint
  pt_mode: linear-elemtype
  eta_mode: linear-elemtype
  sin_phi_mode: linear-elemtype
  cos_phi_mode: linear-elemtype
  energy_mode: linear-elemtype

  gnn_lsh:
    conv_type: gnn_lsh
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout_ff: 0.0
    activation: "elu"
    # gnn-lsh specific parameters
    bin_size: 640
    max_num_bins: 200
    distance_dim: 128
    layernorm: True
    num_node_messages: 2
    ffn_dist_hidden_dim: 128

  gravnet:
    conv_type: gravnet
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout_ff: 0.1
    activation: "elu"
    # gravnet specific parameters
    k: 16
    propagate_dimensions: 32
    space_dimensions: 4

  attention:
    conv_type: attention
    embedding_dim: 256
    width: 256
    num_convs: 3
    dropout_ff: 0.1
    dropout_conv_id_mha: 0.1
    dropout_conv_id_ff: 0.1
    dropout_conv_reg_mha: 0.2
    dropout_conv_reg_ff: 0.2
    activation: "elu"
    # attention specific paramters
    num_heads: 8
    attention_type: flash

  mamba:
    conv_type: mamba
    embedding_dim: 1024
    width: 1024
    num_convs: 4
    dropout_ff: 0.0
    activation: "elu"
    # mamba specific paramters
    d_state: 32
    d_conv: 4
    expand: 2

raytune:
  local_dir: # Note: please specify an absolute path
  sched: asha # asha, hyperband
  search_alg: hyperopt # bayes, bohb, hyperopt, nevergrad, scikit
  default_metric: "val_loss"
  default_mode: "min"
  # Tune schedule specific parameters
  asha:
    max_t: 200
    reduction_factor: 4
    brackets: 1
    grace_period: 10
  hyperband:
    max_t: 200
    reduction_factor: 4
  hyperopt:
    n_random_steps: 10
  nevergrad:
    n_random_steps: 10

train_dataset:
  cms:
    physical:
      batch_size: 1
      samples:
        cms_pf_ttbar:
          version: 1.7.0
        cms_pf_qcd:
          version: 1.7.0
        cms_pf_ztt:
          version: 1.7.0
        cms_pf_qcd_high_pt:
          version: 1.7.0
        cms_pf_sms_t1tttt:
          version: 1.7.0
#    gun:
#      batch_size: 50
#      samples:
#        cms_pf_single_electron:
#          version: 1.7.0
#        cms_pf_single_gamma:
#          version: 1.7.0
#        cms_pf_single_pi0:
#          version: 1.7.0
#        cms_pf_single_neutron:
#          version: 1.7.0
#        cms_pf_single_pi:
#          version: 1.7.0
#        cms_pf_single_tau:
#          version: 1.7.0
#        cms_pf_single_mu:
#          version: 1.7.0
#        cms_pf_single_proton:
#          version: 1.7.0
    multiparticlegun:
      batch_size: 10
      samples:
        cms_pf_multi_particle_gun:
          version: 1.7.0

valid_dataset:
  cms:
    physical:
      batch_size: 1
      samples:
        cms_pf_ttbar:
          version: 1.7.0
        cms_pf_qcd:
          version: 1.7.0
        cms_pf_ztt:
          version: 1.7.0
        cms_pf_qcd_high_pt:
          version: 1.7.0
        cms_pf_sms_t1tttt:
          version: 1.7.0
        cms_pf_vbf:
          version: 1.7.0
    gun:
      batch_size: 50
      samples:
        cms_pf_single_electron:
          version: 1.7.0
        cms_pf_single_gamma:
          version: 1.7.0
        cms_pf_single_pi0:
          version: 1.7.0
        cms_pf_single_neutron:
          version: 1.7.0
        cms_pf_single_pi:
          version: 1.7.0
        cms_pf_single_tau:
          version: 1.7.0
        cms_pf_single_mu:
          version: 1.7.0
        cms_pf_single_proton:
          version: 1.7.0
    multiparticlegun:
      batch_size: 10
      samples:
        cms_pf_multi_particle_gun:
          version: 1.7.0


test_dataset:
  cms:
    physical:
      batch_size: 1
      samples:
        cms_pf_ttbar:
          version: 1.7.0
        cms_pf_qcd_high_pt:
          version: 1.7.0
