sbatch mlpf/tallinn/validate_cms_baseline.sh 1
sbatch mlpf/tallinn/validate_cms_baseline.sh 2
sbatch mlpf/tallinn/validate_cms_baseline.sh 3
sbatch mlpf/tallinn/validate_cms_baseline.sh 4
sbatch mlpf/tallinn/validate_cms_baseline.sh 5
sbatch mlpf/tallinn/validate_cms_baseline.sh 6
sbatch mlpf/tallinn/validate_cms_baseline.sh 7
sbatch mlpf/tallinn/validate_cms_baseline.sh 8
sbatch mlpf/tallinn/validate_cms_baseline.sh 9
sbatch mlpf/tallinn/validate_cms_baseline.sh 10
sbatch mlpf/tallinn/validate_cms_baseline.sh 11
sbatch mlpf/tallinn/validate_cms_baseline.sh 12
sbatch mlpf/tallinn/validate_cms_baseline.sh 13
sbatch mlpf/tallinn/validate_cms_baseline.sh 14
sbatch mlpf/tallinn/validate_cms_baseline.sh 15
sbatch mlpf/tallinn/validate_cms_baseline.sh 16
sbatch mlpf/tallinn/validate_cms_baseline.sh 17
sbatch mlpf/tallinn/validate_cms_baseline.sh 18
sbatch mlpf/tallinn/validate_cms_baseline.sh 19
sbatch mlpf/tallinn/validate_cms_baseline.sh 20
sbatch mlpf/tallinn/validate_cms_baseline.sh 21
sbatch mlpf/tallinn/validate_cms_baseline.sh 22
sbatch mlpf/tallinn/validate_cms_baseline.sh 23
sbatch mlpf/tallinn/validate_cms_baseline.sh 24
sbatch mlpf/tallinn/validate_cms_baseline.sh 25
sbatch mlpf/tallinn/validate_cms_baseline.sh 26
sbatch mlpf/tallinn/validate_cms_baseline.sh 27
sbatch mlpf/tallinn/validate_cms_baseline.sh 28
sbatch mlpf/tallinn/validate_cms_baseline.sh 29
sbatch mlpf/tallinn/validate_cms_baseline.sh 30
sbatch mlpf/tallinn/validate_cms_baseline.sh 31
sbatch mlpf/tallinn/validate_cms_baseline.sh 32
sbatch mlpf/tallinn/validate_cms_baseline.sh 33
sbatch mlpf/tallinn/validate_cms_baseline.sh 34
sbatch mlpf/tallinn/validate_cms_baseline.sh 35
sbatch mlpf/tallinn/validate_cms_baseline.sh 36
sbatch mlpf/tallinn/validate_cms_baseline.sh 37
sbatch mlpf/tallinn/validate_cms_baseline.sh 38
sbatch mlpf/tallinn/validate_cms_baseline.sh 39
sbatch mlpf/tallinn/validate_cms_baseline.sh 40
sbatch mlpf/tallinn/validate_cms_baseline.sh 41
sbatch mlpf/tallinn/validate_cms_baseline.sh 42
sbatch mlpf/tallinn/validate_cms_baseline.sh 43
sbatch mlpf/tallinn/validate_cms_baseline.sh 44
sbatch mlpf/tallinn/validate_cms_baseline.sh 45
sbatch mlpf/tallinn/validate_cms_baseline.sh 46
