backend: tensorflow

dataset:
  schema: delphes
  target_particles: gen
  num_input_features: 12
  num_output_features: 7
  #(none=0, track=1, cluster=2)
  num_input_classes: 3
  #(none=0, charged hadron=1, neutral hadron=2, photon=3, electron=4, muon=5) 
  num_output_classes: 6
  num_momentum_outputs: 5
  padded_num_elem_size: 6400
  classification_loss_coef: 1.0
  charge_loss_coef: 1.0
  pt_loss_coef: 100.0
  eta_loss_coef: 100.0
  sin_phi_loss_coef: 100.0
  cos_phi_loss_coef: 100.0
  energy_loss_coef: 100.0
  sum_energy_loss_coef: 0.0
  sum_pt_loss_coef: 0.0
  energy_loss:
    type: Huber
    delta: 1.0
  pt_loss:
    type: Huber
    delta: 1.0
  sin_phi_loss:
    type: Huber
    delta: 0.1
  cos_phi_loss:
    type: Huber
    delta: 0.1
  eta_loss:
    type: Huber
    delta: 0.1

tensorflow:
  eager: no

setup:
  train: yes
  weights:
  weights_config:
  lr: 1e-4
  num_events_train: 45000
  num_events_test: 5000
  num_events_validation: 5000
  num_epochs: 10
  num_val_files: 5
  dtype: float32
  trainable:
  classification_loss_type: categorical_cross_entropy
  lr_schedule: exponentialdecay  # exponentialdecay, onecycle
  optimizer: adam  # adam, adamw, sgd

optimizer:
  adam:
    amsgrad: no
    pcgrad: no
  adamw:
    amsgrad: yes
    weight_decay: 0.001
  sgd:
    nesterov: no
    momentum: 0.9

# LR Schedules
exponentialdecay:
  decay_steps: 10000
  decay_rate: 0.99
  staircase: yes
onecycle:
  mom_min: 0.85
  mom_max: 0.95
  warmup_ratio: 0.3
  div_factor: 25.0
  final_div: 100000.0

sample_weights:
  cls: inverse_sqrt
  charge: signal_only
  pt: signal_only
  eta: signal_only
  sin_phi: signal_only
  cos_phi: signal_only
  energy: signal_only

parameters:
  model: gnn_dense
  input_encoding: default
  node_update_mode: concat
  do_node_encoding: no
  node_encoding_hidden_dim: 128
  combined_graph_layer:
    bin_size: 640
    max_num_bins: 100
    distance_dim: 128
    layernorm: no
    num_node_messages: 1
    dropout: 0.0
    dist_activation: linear
    ffn_dist_num_layers: 1
    ffn_dist_hidden_dim: 128
    kernel:
      type: NodePairGaussianKernel
      dist_mult: 0.1
      clip_value_low: 0.0
    node_message:
      type: GHConvDense
      output_dim: 256
      activation: elu
      normalize_degrees: yes
    activation: elu
  num_graph_layers_common: 3
  num_graph_layers_energy: 3
  output_decoding:
    activation: elu
    regression_use_classification: yes
    dropout: 0.0

    pt_skip_gate: yes
    eta_skip_gate: yes
    phi_skip_gate: yes

    id_dim_decrease: yes
    charge_dim_decrease: yes
    pt_dim_decrease: yes
    eta_dim_decrease: yes
    phi_dim_decrease: yes
    energy_dim_decrease: yes

    id_hidden_dim: 256
    charge_hidden_dim: 256
    pt_hidden_dim: 256
    eta_hidden_dim: 256
    phi_hidden_dim: 256
    energy_hidden_dim: 256

    id_num_layers: 4
    charge_num_layers: 2
    pt_num_layers: 3
    eta_num_layers: 3
    phi_num_layers: 3
    energy_num_layers: 3
    layernorm: yes
    mask_reg_cls0: no

  skip_connection: yes
  debug: no

timing:
  num_ev: 100
  num_iter: 3

exponentialdecay:
  decay_steps: 10000
  decay_rate: 0.99
  staircase: yes

callbacks:
  checkpoint:
    monitor: "val_loss"
  plot_freq: 10
  tensorboard:
    dump_history: yes
    hist_freq: 1

hypertune:
  algorithm: hyperband  # random, bayesian, hyperband
  random:
    objective: val_loss
    max_trials: 100
  bayesian:
    objective: val_loss
    max_trials: 100
    num_initial_points: 2
  hyperband:
    objective: val_loss
    max_epochs: 100
    factor: 3
    iterations: 1
    executions_per_trial: 1

raytune:
  local_dir:  # Note: please specify an absolute path
  sched: "asha"  # asha, hyperband
  parameters:
    # optimizer parameters
    lr: [1e-4]
    batch_size: [32]
    expdecay_decay_steps: [10000]
    # model parameters
    combined_graph_layer:
      layernorm: [False]
      hidden_dim: [64, 128, 256]
      distance_dim: [128, 256]
      num_node_messages: [1]
      node_message:
        normalize_degrees: [True]
        output_dim: [64, 128, 256]
      dropout: [0.0]
      bin_size: [80, 160, 320]
      kernel:
        clip_value_low: [0.0]
    num_graph_layers_common: [2, 3, 4]
    num_graph_layers_energy: [2, 3, 4]
  # Tune schedule specific parameters
  asha:
    max_t: 100
    reduction_factor: 3
    brackets: 1
    grace_period: 5
  hyperband:
    max_t: 100
    reduction_factor: 3

train_test_datasets:
  delphes: 
    batch_per_gpu: 5
    datasets:
      - delphes_pf

validation_dataset: delphes_pf

datasets:
  delphes_pf:
    version: 1.0.0
    data_dir:
    manual_dir:
