backend: tensorflow

dataset:
  schema: delphes
  target_particles: gen
  num_input_features: 12
  num_output_features: 7
  num_input_classes: 3
  num_output_classes: 6
  num_momentum_outputs: 5
  padded_num_elem_size: 6400
  classification_loss_coef: 1.0
  momentum_loss_coef: 1.0
  charge_loss_coef: 1.0
  momentum_loss_coefs:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.001
  raw_path: data/pythia8_ttbar/raw/*.pkl.bz2
  processed_path: data/pythia8_ttbar/tfr/*.tfrecords
  num_files_per_chunk: 5
  validation_file_path: data/pythia8_ttbar/val/*.pkl.bz2

tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 1e-6
  batch_size: 5
  num_events_train: 40000
  num_events_test: 5000
  num_epochs: 300
  num_val_files: -1
  dtype: float16
  trainable: all
  multi_output: no
  lr_schedule: exponentialdecay  # exponentialdecay, onecycle
  optimizer: adam  # adam, adamw, sgd

optimizer:
  adam:
    amsgrad: no
  adamw:
    amsgrad: yes
    weight_decay: 0.001
  sgd:
    nesterov: no
    momentum: 0.9

sample_weights:
  cls: none
  charge: none
  pt: none
  eta: none
  sin_phi: none
  cos_phi: none
  energy: none

parameters:
  model: transformer
  num_layers: 4
  d_model: 128
  num_heads: 4
  dff: 128
  support: 32
  skip_connection: yes
  dropout: 0.2

exponentialdecay:
  decay_steps: 10000
  decay_rate: 0.99
  staircase: yes
