backend: tensorflow

dataset:
  schema: delphes
  target_particles: gen
  num_input_features: 12
  num_output_features: 7
  #(none=0, track=1, cluster=2)
  num_input_classes: 3
  num_output_classes: 6
  num_momentum_outputs: 5
  padded_num_elem_size: 6400
  classification_loss_coef: 1.0
  momentum_loss_coef: 1.0
  charge_loss_coef: 1.0
  pt_loss_coef: 1.0
  eta_loss_coef: 1.0
  sin_phi_loss_coef: 1.0
  cos_phi_loss_coef: 1.0
  energy_loss_coef: 0.001
  momentum_loss_coefs:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.001
  raw_path: ../data/mlpf_zenodo/pythia8_ttbar/raw/*.pkl.bz2
  processed_path: ../data/mlpf_zenodo/pythia8_ttbar/tfr/*.tfrecords
  num_files_per_chunk: 5
  validation_file_path: ../data/mlpf_zenodo/pythia8_qcd/val/*.pkl.bz2

tensorflow:
  eager: no

setup:
  train: yes
  weights:
  weights_config: all
  lr: 1e-5
  batch_size: 16
  num_events_train: 40000
  num_events_test: 5000
  num_epochs: 250
  num_val_files: -1
  dtype: float32
  trainable: all
  multi_output: yes
  classification_loss_type: categorical_cross_entropy
  lr_schedule: onecycle  # exponentialdecay, onecycle
  optimizer: adam  # adam, adamw, sgd

optimizer:
  adam:
    amsgrad: no
  adamw:
    amsgrad: yes
    weight_decay: 0.001
  sgd:
    nesterov: no
    momentum: 0.9

sample_weights:
  cls: none
  charge: none
  pt: none
  eta: none
  sin_phi: none
  cos_phi: none
  energy: none

parameters:
  model: gnn
  bin_size: 128
  num_convs_id: 2
  num_convs_reg: 2
  num_hidden_id_enc: 2
  num_hidden_id_dec: 2
  num_hidden_reg_enc: 2
  num_hidden_reg_dec: 2
  num_neighbors: 16 
  hidden_dim_id: 256
  hidden_dim_reg: 256
  distance_dim: 256
  dropout: 0.2
  dist_mult: 1.0
  activation: elu
  skip_connection: True

timing:
  num_ev: 100
  num_iter: 3

exponentialdecay:
  decay_steps: 10000
  decay_rate: 0.99
  staircase: yes

onecycle:
  mom_min: 0.85
  mom_max: 0.95
  warmup_ratio: 0.3
  div_factor: 25.0
  final_div: 100000.0