backend: pytorch

model:
  gnn-lsh:
    conv_type: gnn-lsh
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout: 0.0

  gravnet:
    conv_type: gravnet
    embedding_dim: 512
    width: 512
    num_convs: 3
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: 0.0

  attention:
    conv_type: attention
    embedding_dim: 128
    width: 128
    num_convs: 2
    dropout: 0.0

train_dataset:
  cms:
    cms_pf_ttbar:
      version: 1.6.0
      batch_size: 2
valid_dataset:
  cms:
    cms_pf_ttbar:
      version: 1.6.0
      batch_size: 2
test_dataset:
  cms:
    cms_pf_ttbar:
      version: 1.6.0
      batch_size: 2
