backend: pytorch

dataset: cms
data_dir:
gpus:
gpu_batch_multiplier: 1
load:
num_epochs: 2
patience: 20
lr: 0.0001
lr_schedule: constant  # constant, cosinedecay, onecycle
conv_type: gravnet
ntrain:
ntest:
nvalid: 500
num_workers: 0
prefetch_factor:
checkpoint_freq:
comet_name: particleflow-pt
comet_offline: False
comet_step_freq: 10

model:
  gnn_lsh:
    conv_type: gnn_lsh
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout: 0.0
    activation: "elu"
    # gnn-lsh specific parameters
    bin_size: 640
    max_num_bins: 200
    distance_dim: 128
    layernorm: True
    num_node_messages: 2
    ffn_dist_hidden_dim: 128

  gravnet:
    conv_type: gravnet
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout: 0.0
    activation: "elu"
    # gravnet specific parameters
    k: 16
    propagate_dimensions: 32
    space_dimensions: 4

  attention:
    conv_type: attention
    embedding_dim: 256
    width: 256
    num_convs: 3
    dropout: 0.0
    activation: "elu"
    # attention specific paramters
    num_heads: 2

  mamba:
    conv_type: mamba
    embedding_dim: 128
    width: 128
    num_convs: 2
    dropout: 0.0
    activation: "elu"
    # transformer specific paramters
    num_heads: 2
    # mamba specific paramters
    d_state: 16
    d_conv: 4
    expand: 2

train_dataset:
  cms:
    physical:
      batch_size: 2
      samples:
        cms_pf_ttbar:
          version: 1.6.0

valid_dataset:
  cms:
    physical:
      batch_size: 2
      samples:
        cms_pf_ttbar:
          version: 1.6.0

test_dataset:
  cms:
    physical:
      batch_size: 2
      samples:
        cms_pf_ttbar:
          version: 1.6.0
