backend: pytorch

model:
  gnn-lsh:
    conv_type: gnn-lsh
    embedding_dim: 36
    width: 128
    num_convs: 2
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: True

  gravnet:
    conv_type: gravnet
    embedding_dim: 36
    width: 128
    num_convs: 2
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: True

  attention:
    conv_type: attention
    embedding_dim: 128
    width: 128
    num_convs: 2
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: True

train_dataset:
  cms:
    cms_pf_ttbar:
      version: 1.6.0
      batch_size: 2
test_dataset:
  cms:
    cms_pf_ttbar:
      version: 1.6.0
      batch_size: 2
