backend: pytorch

dataset: cms
data_dir:
gpus: "0"
gpu_batch_multiplier: 1
load:
num_epochs: 2
patience: 20
lr: 1e_4
conv_type: gnn_lsh
ntrain:
ntest:
num_workers: 1
prefetch_factor: 2

model:
  gnn_lsh:
    conv_type: gnn_lsh
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout: 0.0

  gravnet:
    conv_type: gravnet
    embedding_dim: 512
    width: 512
    num_convs: 3
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: 0.0

  attention:
    conv_type: attention
    embedding_dim: 128
    width: 128
    num_convs: 2
    dropout: 0.0

test_dataset:
  cms:
    cms_pf_qcd_high_pt:
      version: 1.6.0
      batch_size: 1
