backend: pytorch

dataset: cms
data_dir:
gpus: "0"
gpu_batch_multiplier: 1
load:
num_epochs: 10
patience: 20
lr: 0.0001
conv_type: gravnet
ntrain: 500
ntest: 500
nvalid: 500
num_workers: 0
prefetch_factor:
checkpoint_freq:
comet_name: particleflow-pt
comet_offline: False
comet_step_freq: 10

model:
  gnn_lsh:
    conv_type: gnn_lsh
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout: 0.0

  gravnet:
    conv_type: gravnet
    embedding_dim: 512
    width: 512
    num_convs: 3
    k: 16
    propagate_dimensions: 32
    space_dimensions: 4
    dropout: 0.0

  attention:
    conv_type: attention
    embedding_dim: 256
    width: 256
    num_convs: 3
    dropout: 0.0

raytune:
  local_dir: # Note: please specify an absolute path
  sched: asha # asha, hyperband
  search_alg: hyperopt # bayes, bohb, hyperopt, nevergrad, scikit
  default_metric: "val_loss"
  default_mode: "min"
  # Tune schedule specific parameters
  asha:
    max_t: 200
    reduction_factor: 4
    brackets: 1
    grace_period: 10
  hyperband:
    max_t: 200
    reduction_factor: 4
  hyperopt:
    n_random_steps: 10
  nevergrad:
    n_random_steps: 10

train_dataset:
  cms:
    physical:
      batch_size: 1
      samples:
        cms_pf_ttbar:
          version: 1.6.0
        cms_pf_qcd:
          version: 1.6.0

valid_dataset:
  cms:
    physical:
      batch_size: 1
      samples:
        cms_pf_qcd_high_pt:
          version: 1.6.0

test_dataset:
  cms:
    physical:
      batch_size: 1
      samples:
        cms_pf_qcd_high_pt:
          version: 1.6.0
