backend: pytorch

dataset: delphes
data_dir:
gpus: "0"
gpu_batch_multiplier: 1
load:
num_epochs: 2
patience: 20
lr: 0.0001
conv_type: gnn_lsh
ntrain:
ntest:
num_workers: 0
prefetch_factor:

model:
  gnn_lsh:
    conv_type: gnn_lsh
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout: 0.0

  gravnet:
    conv_type: gravnet
    embedding_dim: 512
    width: 512
    num_convs: 3
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: 0.0

  attention:
    conv_type: attention
    embedding_dim: 128
    width: 128
    num_convs: 2
    dropout: 0.0

train_dataset:
  delphes:
    delphes_ttbar_pf:
      version: 1.2.0
      batch_size: 10
    delphes_qcd_pf:
      version: 1.2.0
      batch_size: 10

valid_dataset:
  delphes:
    delphes_qcd_pf:
      version: 1.2.0
      batch_size: 10

test_dataset:
  delphes:
    delphes_ttbar_pf:
      version: 1.2.0
      batch_size: 10
    delphes_qcd_pf:
      version: 1.2.0
      batch_size: 10
