backend: pytorch

model:
  gnn-lsh:
    conv_type: gnn-lsh
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout: 0.0

  gravnet:
    conv_type: gravnet
    embedding_dim: 512
    width: 512
    num_convs: 3
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: 0.0

  attention:
    conv_type: attention
    embedding_dim: 128
    width: 128
    num_convs: 2
    dropout: 0.0

train_dataset:
  clic:
    clic_edm_qq_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pu10_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ww_fullhad_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_zh_tautau_pf:
      version: 1.5.0
      batch_size: 100

valid_dataset:
  clic:
    clic_edm_qq_pf:
      version: 1.5.0
      batch_size: 100

test_dataset:
  clic:
    clic_edm_qq_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pu10_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ww_fullhad_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_zh_tautau_pf:
      version: 1.5.0
      batch_size: 100
