backend: pytorch

dataset: clic
data_dir:
gpus: "0"
gpu_batch_multiplier: 1
load:
num_epochs: 2
patience: 20
lr: 0.0001
conv_type: gnn_lsh
ntrain:
ntest:
num_workers: 0
prefetch_factor:

model:
  gnn_lsh:
    conv_type: gnn_lsh
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout: 0.0

  gravnet:
    conv_type: gravnet
    embedding_dim: 512
    width: 512
    num_convs: 3
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: 0.0

  attention:
    conv_type: attention
    embedding_dim: 128
    width: 128
    num_convs: 2
    dropout: 0.0

raytune:
  local_dir: /mnt/ceph/users/ewulff/ray_results/  # Note: please specify an absolute path
  sched:  # asha, hyperband
  search_alg:  # bayes, bohb, hyperopt, nevergrad, scikit
  default_metric: "val_loss"
  default_mode: "min"
  # Tune schedule specific parameters
  asha:
    max_t: 200
    reduction_factor: 4
    brackets: 1
    grace_period: 10
  hyperband:
    max_t: 200
    reduction_factor: 4
  hyperopt:
    n_random_steps: 10
  nevergrad:
    n_random_steps: 10

train_dataset:
  clic:
    clic_edm_qq_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pu10_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ww_fullhad_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_zh_tautau_pf:
      version: 1.5.0
      batch_size: 100

valid_dataset:
  clic:
    clic_edm_qq_pf:
      version: 1.5.0
      batch_size: 100

test_dataset:
  clic:
    clic_edm_qq_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pu10_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ww_fullhad_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_zh_tautau_pf:
      version: 1.5.0
      batch_size: 100
