backend: pytorch

dataset: cms
data_dir:
gpus: "0"
gpu_batch_multiplier: 1
load:
num_epochs: 2
patience: 20
lr: 0.0001
conv_type: gnn_lsh
ntrain:
ntest:
nvalid: 500
num_workers: 0
prefetch_factor:
checkpoint_freq:

model:
  gnn_lsh:
    conv_type: gnn_lsh
    embedding_dim: 512
    width: 512
    num_convs: 3
    dropout: 0.0

  gravnet:
    conv_type: gravnet
    embedding_dim: 512
    width: 512
    num_convs: 3
    k: 16
    propagate_dimensions: 32
    space_dimensions: 4
    dropout: 0.0

  attention:
    conv_type: attention
    embedding_dim: 256
    width: 256
    num_convs: 3
    dropout: 0.0

train_dataset:
  cms:
    physical:
      batch_size: 1
      samples:
        cms_pf_ttbar:
          version: 1.6.0
        cms_pf_qcd:
          version: 1.6.0

valid_dataset:
  cms:
    physical:
      batch_size: 1
      samples:
        cms_pf_qcd_high_pt:
          version: 1.6.0

test_dataset:
  cms:
    physical:
      batch_size: 1
      samples:
        cms_pf_qcd_high_pt:
          version: 1.6.0
