FROM vault.habana.ai/gaudi-docker/1.9.0/ubuntu20.04/habanalabs/tensorflow-installer-tf-cpu-2.11.0:latest

LABEL maintainer="Javier Duarte <jduarte@ucsd.edu>"

COPY requirements.txt .
COPY requirements_nodeps.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements_nodeps.txt --no-deps
