FROM vault.habana.ai/gaudi-docker/1.13.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.0:latest
LABEL maintainer="Javier Duarte <jduarte@ucsd.edu>"

RUN apt-get update && \
    apt-get install -qq -y graphviz graphviz-dev

COPY requirements_base.txt .
RUN pip install -r requirements_base.txt
