FROM vault.habana.ai/gaudi-docker/1.6.0/ubuntu20.04/habanalabs/tensorflow-installer-tf-cpu-2.9.1:latest
LABEL maintainer="Javier Duarte <jduarte@ucsd.edu>"

COPY requirements.txt .
COPY requirements_nodeps.txt .
RUN pip install -r requirements.txt
RUN pip install -r requirements_nodeps.txt --no-deps
