FROM vault.habana.ai/gaudi-docker/1.20.0/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest
LABEL maintainer="Javier Duarte <jduarte@ucsd.edu>"

RUN apt-get update && \
    apt-get install -qq -y graphviz graphviz-dev

COPY requirements.txt .
RUN pip install -r requirements.txt
