import torch
import torch.nn as nn
from torch.nn import functional as F
from torch.nn.attention import SDPBackend, sdpa_kernel
import time
import sys
import random
import math
import einops
from einops import rearrange

# Ensure unbuffered output
sys.stdout.reconfigure(line_buffering=True)
sys.stderr.reconfigure(line_buffering=True)

from mlpf.standalone.dsl import HEPTConfig

# --- HEPT Utilities ---
# Adapted from https://github.com/mova/HEPT
# Paper: "HEPT: Hashed Efficient Particle Transformer", https://arxiv.org/abs/2405.21051
# MIT License
# Copyright (c) 2024 Graph-COM
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# Implementation Differences from Official HEPT (HEPT/example/hept.py & HEPT/hept.md):
# 1. Batching & Precision: Supports batched inputs [B, N, D] via flattening. Coordinates
#    and offsets are forced to float32. Note: Large batch sizes (>500) may cause "smearing"
#    of hit coordinates due to float32 precision limits when adding large offsets.
# 2. Query-Key Alignment (Sec 4.3): Implements coordinate-based AND LSH codes via
#    quantile_partition() and get_geo_shift() specifically for HEP 2D eta-phi space.
# 3. Output Projection: HEPTAttention projects to full embedding dim (num_heads * dim_per_head)
#    instead of dim_per_head as seen in some official examples.
# 4. Numerical Stability & Gradient Safety: Core RBF distance and weighted sums are performed
#    in float32. Includes 1e-20 eps and crops outputs back to raw_size before projection
#    to ensure stable training and finite gradients in highly sparse attention patterns.
# 5. Backbone Integration: Uses ELU activations and integrated PositionalEncoding
#    as used in the paper's Tracking experiments.


def uniform(a, b, shape, device="cpu"):
    return (b - a) * torch.rand(shape, device=device) + a


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    """
    Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`,
    but values outside :math:`[a, b]` are redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """

    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower bound values in standard normal
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2lo-1, 2up-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def quantile_partition(X, n_hashes, n_buckets, device="cpu"):
    B, N, D = X.shape
    # X: [B, N, D]
    # We want to partition into n_buckets based on quantiles for each hash.
    # To get different hashes, we can project X onto random directions.
    # For HEP, we just project onto 2D eta-phi or 3D x-y-z.

    # Projection directions: [n_hashes, D]
    directions = torch.randn(n_hashes, D, device=device)
    projections = torch.matmul(X, directions.T)  # [B, N, n_hashes]

    # For each hash, find bucket boundaries
    # buckets: [n_hashes, B, N]
    indices = torch.zeros(n_hashes, B, N, dtype=torch.long, device=device)

    for h in range(n_hashes):
        proj_h = projections[:, :, h]  # [B, N]
        # Sort and find boundaries
        # This is a bit slow for large N, but necessary for quantile partitioning.
        sorted_proj, _ = torch.sort(proj_h, dim=1)

        # Boundaries for n_buckets
        for b in range(1, n_buckets):
            edge_idx = int(b * N / n_buckets)
            # Thresholds: [B, 1]
            thresholds = sorted_proj[:, edge_idx : edge_idx + 1]
            indices[h] += (proj_h >= thresholds).long()

    return indices


def get_geo_shift(X, n_hashes, n_buckets, device="cpu"):
    # Official HEPT uses coordinate shifts to create multi-hash
    # X_shifted = X + shift
    # For simplicity, we use random projections like above.
    return quantile_partition(X, n_hashes, n_buckets, device)


class HEPTAttention(nn.Module):
    def __init__(self, embedding_dim, num_heads, block_size=100, n_hashes=3, num_regions=140, num_w_per_dist=10):
        super(HEPTAttention, self).__init__()
        self.embedding_dim = embedding_dim
        self.num_heads = num_heads
        self.head_dim = embedding_dim // num_heads
        self.block_size = block_size
        self.n_hashes = n_hashes
        self.num_regions = num_regions
        self.num_w_per_dist = num_w_per_dist

        self.qkv_proj = nn.Linear(embedding_dim, 3 * embedding_dim)
        self.out_proj = nn.Linear(embedding_dim, embedding_dim)

    def forward(self, x, mask, X_coords):
        B, N, D = x.shape
        H = self.num_heads
        D_h = self.head_dim

        qkv = self.qkv_proj(x).reshape(B, N, 3, H, D_h)
        q, k, v = qkv[:, :, 0], qkv[:, :, 1], qkv[:, :, 2]

        # 1. Coordinate-based partitioning
        # X_coords: [B, N, 2] (eta, phi) or [B, N, 3] (x, y, z)
        # indices: [n_hashes, B, N]
        indices = get_geo_shift(X_coords, self.n_hashes, self.num_regions, device=x.device)

        # 2. Local Attention within regions
        # This is a simplified version of the sparse HEPT attention.
        # We process each hash and aggregate.
        outputs = []
        for h in range(self.n_hashes):
            idx_h = indices[h]  # [B, N]

            # Sort by region index to group elements
            # This is the "hashing" part.
            sorted_idx = torch.argsort(idx_h, dim=1)

            # Reorder q, k, v
            q_s = torch.gather(q, 1, sorted_idx.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, H, D_h))
            k_s = torch.gather(k, 1, sorted_idx.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, H, D_h))
            v_s = torch.gather(v, 1, sorted_idx.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, H, D_h))

            # Chunk into blocks of block_size
            # N_pad to multiple of block_size
            pad = (self.block_size - (N % self.block_size)) % self.block_size
            if pad > 0:
                q_s = F.pad(q_s, (0, 0, 0, 0, 0, pad))
                k_s = F.pad(k_s, (0, 0, 0, 0, 0, pad))
                v_s = F.pad(v_s, (0, 0, 0, 0, 0, pad))

            N_p = N + pad
            n_blocks = N_p // self.block_size

            q_b = q_s.reshape(B, n_blocks, self.block_size, H, D_h).transpose(2, 3)
            k_b = k_s.reshape(B, n_blocks, self.block_size, H, D_h).transpose(2, 3)
            v_b = v_s.reshape(B, n_blocks, self.block_size, H, D_h).transpose(2, 3)

            # Local scaled dot-product attention
            with sdpa_kernel([SDPBackend.FLASH_ATTENTION, SDPBackend.EFFICIENT_ATTENTION, SDPBackend.MATH]):
                out_b = F.scaled_dot_product_attention(q_b, k_b, v_b)

            out_s = out_b.transpose(2, 3).reshape(B, N_p, H, D_h)
            if pad > 0:
                out_s = out_s[:, :N, :, :]

            # Unsort
            # unsort_idx: [B, N]
            unsort_idx = torch.argsort(sorted_idx, dim=1)
            out_h = torch.gather(out_s, 1, unsort_idx.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, H, D_h))
            outputs.append(out_h)

        # Aggregate across hashes (mean)
        out = torch.stack(outputs, dim=0).mean(dim=0)
        out = out.reshape(B, N, self.embedding_dim)
        return self.out_proj(out)


class SimpleMultiheadAttention(nn.Module):
    def __init__(self, embed_dim, num_heads, dropout=0.0):
        super(SimpleMultiheadAttention, self).__init__()
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.head_dim = embed_dim // num_heads
        self.q_proj = nn.Linear(embed_dim, embed_dim)
        self.k_proj = nn.Linear(embed_dim, embed_dim)
        self.v_proj = nn.Linear(embed_dim, embed_dim)
        self.out_proj = nn.Linear(embed_dim, embed_dim)
        self.dropout_p = dropout

    def forward(self, q, k, v, key_padding_mask=None, return_attn=False):
        B, N, D = q.shape
        H = self.num_heads
        D_h = self.head_dim

        q = self.q_proj(q).reshape(B, N, H, D_h).transpose(1, 2)
        k = self.k_proj(k).reshape(B, N, H, D_h).transpose(1, 2)
        v = self.v_proj(v).reshape(B, N, H, D_h).transpose(1, 2)

        attn_mask = None
        if key_padding_mask is not None:
            # key_padding_mask: [B, N] where 1 is valid, 0 is padding
            # SDPA expects [B, 1, 1, N] mask
            attn_mask = key_padding_mask.bool().unsqueeze(1).unsqueeze(2)

        if return_attn:
            # Manual calculation if we need weights
            attn_weights = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(D_h)
            if attn_mask is not None:
                attn_weights = attn_weights.masked_fill(~attn_mask, float("-inf"))
            attn_weights = F.softmax(attn_weights, dim=-1)
            out = torch.matmul(attn_weights, v)
        else:
            with sdpa_kernel([SDPBackend.FLASH_ATTENTION, SDPBackend.EFFICIENT_ATTENTION, SDPBackend.MATH]):
                out = F.scaled_dot_product_attention(q, k, v, attn_mask=attn_mask, dropout_p=self.dropout_p if self.training else 0.0)
            attn_weights = None

        out = out.transpose(1, 2).reshape(B, N, D)
        return self.out_proj(out), attn_weights


# --- Backbones ---


class HEPTAttentionLayer(nn.Module):
    def __init__(self, embedding_dim, num_heads, width, dropout=0.1, pos=False, **kwargs):
        super(HEPTAttentionLayer, self).__init__()
        self.embedding_dim = embedding_dim
        self.num_heads = num_heads
        self.width = width
        self.dropout_p = dropout
        self.pos = pos

        hept_conf = {k: v for k, v in kwargs.items() if k in ["block_size", "n_hashes", "num_regions", "num_w_per_dist"]}
        self.mha = HEPTAttention(embedding_dim, num_heads, **hept_conf)
        self.norm0 = nn.LayerNorm(embedding_dim)
        self.norm1 = nn.LayerNorm(embedding_dim)
        self.seq = nn.Sequential(nn.Linear(embedding_dim, width), nn.GELU(), nn.Linear(width, embedding_dim), nn.GELU())
        self.dropout = nn.Dropout(dropout)
        self.pos_embed = PositionalEncoding(embedding_dim) if pos else None

    def extra_repr(self):
        return f"embedding_dim={self.embedding_dim}, num_heads={self.num_heads}, width={self.width}, dropout={self.dropout_p}, pos={self.pos}"

    def forward(self, x, mask, X=None, return_attn=False):
        # x: [B, N, D]
        # mask: [B, N] (valid entries)
        # X: [B, N, 55] (original features for coordinates)
        if self.pos_embed and X is not None:
            x = self.pos_embed(x, X)

        if mask is not None:
            mask_ = mask.unsqueeze(-1)

        residual = x
        x_norm = self.norm0(x)
        if mask is not None:
            x_norm = x_norm * mask_

        # Use eta, phi for partitioning [B, N, 2]
        coords = X[..., 2:4] if X is not None else torch.zeros((x.shape[0], x.shape[1], 2), device=x.device)
        mha_out = self.mha(x_norm, mask, coords)
        x = residual + mha_out

        residual = x
        x_norm = self.norm1(x)
        ffn_out = self.seq(x_norm)
        ffn_out = self.dropout(ffn_out)

        x = residual + ffn_out
        if mask is not None:
            x = x * mask_

        if return_attn:
            return x, None  # HEPT sparse attention matrix not easily reconstructed for full N
        return x


class GlobalAttentionLayer(nn.Module):
    def __init__(self, embedding_dim, num_heads, width, dropout=0.1, pos=False, **kwargs):
        super(GlobalAttentionLayer, self).__init__()
        self.embedding_dim = embedding_dim
        self.num_heads = num_heads
        self.width = width
        self.dropout_p = dropout
        self.pos = pos

        self.mha = SimpleMultiheadAttention(embedding_dim, num_heads, dropout=dropout)
        self.norm0 = nn.LayerNorm(embedding_dim)
        self.norm1 = nn.LayerNorm(embedding_dim)
        self.seq = nn.Sequential(nn.Linear(embedding_dim, width), nn.GELU(), nn.Linear(width, embedding_dim), nn.GELU())
        self.dropout = nn.Dropout(dropout)
        self.pos_embed = PositionalEncoding(embedding_dim) if pos else None

    def extra_repr(self):
        return f"embedding_dim={self.embedding_dim}, num_heads={self.num_heads}, width={self.width}, dropout={self.dropout_p}, pos={self.pos}"

    def forward(self, x, mask, X=None, return_attn=False):
        if self.pos_embed and X is not None:
            x = self.pos_embed(x, X)

        # x: [B, N, D]
        # mask: [B, N]
        if mask is not None:
            mask_ = mask.unsqueeze(-1)

        residual = x
        x_norm = self.norm0(x)
        if mask is not None:
            x_norm = x_norm * mask_

        mha_out, attn = self.mha(x_norm, x_norm, x_norm, key_padding_mask=mask, return_attn=return_attn)
        x = residual + mha_out

        residual = x
        x_norm = self.norm1(x)
        ffn_out = self.seq(x_norm)
        ffn_out = self.dropout(ffn_out)

        x = residual + ffn_out
        if mask is not None:
            x = x * mask_
        if return_attn:
            return x, attn
        return x


class StandardAttentionLayer(nn.Module):
    """
    Standard $O(N^2)$ attention using fused kernels (FlashAttention-2 when available).
    Reference: "Attention Is All You Need", https://arxiv.org/abs/1706.03762

    Notation:
    - X: Input sequence of shape [B, N, D]
    - Q, K, V: Projected query, key, value matrices of shape [B, N, H, D_h] (H=heads, D_h=head_dim)
    - W_q, W_k, W_v, W_o: Learnable projection weight matrices
    - N: Sequence length

    Mechanism (per head):
    1. Q, K, V = X * W_q, X * W_k, X * W_v          -> shape [B, N, H, D_h]
    2. Attention = Softmax( (Q * K^T) / √D_h )      -> shape [B, H, N, N]
    3. Context = Attention * V                      -> shape [B, H, N, D_h]
    4. Out = Context * W_o                          -> shape [B, N, D]
    """

    def __init__(self, embedding_dim, num_heads, width, dropout=0.1, pos=False, **kwargs):
        super(StandardAttentionLayer, self).__init__()
        self.embedding_dim = embedding_dim
        self.num_heads = num_heads
        self.width = width
        self.dropout_p = dropout
        self.pos = pos
        self.head_dim = embedding_dim // num_heads

        self.q_proj = nn.Linear(embedding_dim, embedding_dim)
        self.k_proj = nn.Linear(embedding_dim, embedding_dim)
        self.v_proj = nn.Linear(embedding_dim, embedding_dim)
        self.out_proj = nn.Linear(embedding_dim, embedding_dim)

        self.norm0 = nn.LayerNorm(embedding_dim)
        self.norm1 = nn.LayerNorm(embedding_dim)
        self.seq = nn.Sequential(nn.Linear(embedding_dim, width), nn.GELU(), nn.Linear(width, embedding_dim), nn.GELU())
        self.dropout = nn.Dropout(dropout)
        self.pos_embed = PositionalEncoding(embedding_dim) if pos else None

    def extra_repr(self):
        return f"embedding_dim={self.embedding_dim}, num_heads={self.num_heads}, width={self.width}, dropout={self.dropout_p}, pos={self.pos}"

    def forward(self, x, mask, X=None, return_attn=False):
        if self.pos_embed and X is not None:
            x = self.pos_embed(x, X)

        B, N, D = x.shape
        if mask is not None:
            # Ensure elements with zero features are also masked
            mask = mask * (x.abs().sum(dim=-1) > 1e-6).float()
            mask_ = mask.unsqueeze(-1)

        residual = x
        x_norm = self.norm0(x)
        if mask is not None:
            x_norm = x_norm * mask_

        q = self.q_proj(x_norm).reshape(B, N, self.num_heads, self.head_dim).transpose(1, 2)
        k = self.k_proj(x_norm).reshape(B, N, self.num_heads, self.head_dim).transpose(1, 2)
        v = self.v_proj(x_norm).reshape(B, N, self.num_heads, self.head_dim).transpose(1, 2)

        # If mask is provided, use it as attn_mask for proper padding handling
        attn_mask = mask.bool().unsqueeze(1).unsqueeze(2) if mask is not None else None

        if return_attn:
            attn_weights = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.head_dim)
            if attn_mask is not None:
                attn_weights = attn_weights.masked_fill(~attn_mask, float("-inf"))
            attn_weights = F.softmax(attn_weights, dim=-1)
            mha_out = torch.matmul(attn_weights, v)
        else:
            with sdpa_kernel([SDPBackend.FLASH_ATTENTION, SDPBackend.EFFICIENT_ATTENTION, SDPBackend.MATH]):
                mha_out = F.scaled_dot_product_attention(q, k, v, attn_mask=attn_mask, dropout_p=self.dropout.p if self.training else 0.0)
            attn_weights = None

        mha_out = mha_out.transpose(1, 2).reshape(B, N, D)
        mha_out = self.out_proj(mha_out)

        x = residual + self.dropout(mha_out)

        residual = x
        x_norm = self.norm1(x)
        ffn_out = self.seq(x_norm)
        ffn_out = self.dropout(ffn_out)

        x = residual + ffn_out
        if mask is not None:
            x = x * mask_
        if return_attn:
            return x, attn_weights
        return x


class FastformerAttention(nn.Module):
    def __init__(self, embedding_dim, num_heads):
        super(FastformerAttention, self).__init__()
        self.embedding_dim = embedding_dim
        self.num_heads = num_heads
        self.head_dim = embedding_dim // num_heads

        self.weight_q = nn.Linear(embedding_dim, embedding_dim)
        self.weight_k = nn.Linear(embedding_dim, embedding_dim)
        self.weight_v = nn.Linear(embedding_dim, embedding_dim)

        self.attention_q = nn.Linear(embedding_dim, num_heads)
        self.attention_k = nn.Linear(embedding_dim, num_heads)

        self.out_proj = nn.Linear(embedding_dim, embedding_dim)

    def forward(self, x, mask):
        # x: [B, N, D]
        # mask: [B, N]
        B, N, D = x.shape

        q = self.weight_q(x)  # [B, N, D]
        k = self.weight_k(x)  # [B, N, D]
        v = self.weight_v(x)  # [B, N, D]

        # Query attention
        alpha = self.attention_q(q)  # [B, N, H]
        if mask is not None:
            alpha = alpha.masked_fill(~mask.bool().unsqueeze(-1), float("-inf"))
        alpha = F.softmax(alpha, dim=1)  # [B, N, H]

        global_q = torch.sum(alpha.unsqueeze(-1) * q.reshape(B, N, self.num_heads, self.head_dim), dim=1)  # [B, H, D_h]

        # Key attention
        p = k * global_q.repeat(1, 1, N).reshape(B, N, D)
        beta = self.attention_k(p)  # [B, N, H]
        if mask is not None:
            beta = beta.masked_fill(~mask.bool().unsqueeze(-1), float("-inf"))
        beta = F.softmax(beta, dim=1)  # [B, N, H]

        global_k = torch.sum(beta.unsqueeze(-1) * p.reshape(B, N, self.num_heads, self.head_dim), dim=1)  # [B, H, D_h]

        # Value interaction
        out = v * global_k.repeat(1, 1, N).reshape(B, N, D)
        return self.out_proj(out)


class FastformerAttentionLayer(nn.Module):
    def __init__(self, embedding_dim, num_heads, width, dropout=0.1, pos=False, **kwargs):
        super(FastformerAttentionLayer, self).__init__()
        self.embedding_dim = embedding_dim
        self.num_heads = num_heads
        self.width = width
        self.dropout_p = dropout
        self.pos = pos

        self.attn = FastformerAttention(embedding_dim, num_heads)
        self.norm0 = nn.LayerNorm(embedding_dim)
        self.norm1 = nn.LayerNorm(embedding_dim)
        self.seq = nn.Sequential(nn.Linear(embedding_dim, width), nn.GELU(), nn.Linear(width, embedding_dim), nn.GELU())
        self.dropout = nn.Dropout(dropout)
        self.pos_embed = PositionalEncoding(embedding_dim) if pos else None

    def extra_repr(self):
        return f"embedding_dim={self.embedding_dim}, num_heads={self.num_heads}, width={self.width}, dropout={self.dropout_p}, pos={self.pos}"

    def forward(self, x, mask, X=None, return_attn=False):
        if self.pos_embed and X is not None:
            x = self.pos_embed(x, X)

        if mask is not None:
            mask_ = mask.unsqueeze(-1)

        residual = x
        x_norm = self.norm0(x)
        if mask is not None:
            x_norm = x_norm * mask_

        mha_out = self.attn(x_norm, mask)
        x = residual + mha_out

        residual = x
        x_norm = self.norm1(x)
        ffn_out = self.seq(x_norm)
        ffn_out = self.dropout(ffn_out)

        x = residual + ffn_out
        if mask is not None:
            x = x * mask_
        if return_attn:
            return x, None
        return x


# Registry of available attention layers
SUPPORTED_ATTENTION_LAYERS = {
    "hept": HEPTAttentionLayer,
    "global": GlobalAttentionLayer,
    "standard": StandardAttentionLayer,
    "fastformer": FastformerAttentionLayer,
}


def ffn(input_dim, output_dim, width, dropout=0.1):
    return nn.Sequential(
        nn.Linear(input_dim, width),
        nn.GELU(),
        nn.LayerNorm(width),
        nn.Dropout(dropout),
        nn.Linear(width, output_dim),
    )


class PositionalEncoding(nn.Module):
    def __init__(self, embedding_dim):
        super(PositionalEncoding, self).__init__()
        self.proj = nn.Linear(2, embedding_dim)

    def forward(self, x, X):
        # Extract eta and phi
        eta = X[..., 2:3]
        phi = torch.atan2(X[..., 3:4], X[..., 4:5])
        coords = torch.cat([eta, phi], dim=-1)  # [B, N, 2]
        return x + self.proj(coords)


class RegressionOutput(nn.Module):
    def __init__(self, mode, embed_dim, width, elemtypes, dropout=0.1):
        super(RegressionOutput, self).__init__()
        self.mode = mode  # "direct", "additive", "multiplicative", "linear"
        self.embed_dim = embed_dim
        self.width = width
        self.dropout_p = dropout
        self.elemtypes = elemtypes
        if mode == "linear":
            self.nn = ffn(embed_dim, 2 * len(elemtypes), width, dropout=dropout)
        else:
            self.nn = ffn(embed_dim, len(elemtypes), width, dropout=dropout)

    def extra_repr(self):
        return f"mode={self.mode}, embed_dim={self.embed_dim}, width={self.width}, dropout={self.dropout_p}"

    def forward(self, X, x, orig_value):
        # X: [B, N, 25] or [B, N, 55] (original features)
        # x: [B, N, D] (latent representation)
        # orig_value: [B, N, 1] (the feature to regress from)

        nn_out = self.nn(x)
        elemtype_mask = torch.stack([X[..., 0] == elemtype for elemtype in self.elemtypes], dim=-1)

        if self.mode == "linear":
            # nn_out: [B, N, 2 * len(elemtypes)]
            num_types = len(self.elemtypes)
            a_all = nn_out[..., :num_types]
            b_all = nn_out[..., num_types:]
            a = torch.sum(elemtype_mask * a_all, dim=-1, keepdim=True)
            b = torch.sum(elemtype_mask * b_all, dim=-1, keepdim=True)
            return orig_value * a + b
        else:
            res = torch.sum(elemtype_mask * nn_out, dim=-1, keepdim=True)
            if self.mode == "direct":
                return res
            elif self.mode == "additive":
                return orig_value + res
            elif self.mode == "multiplicative":
                return orig_value * res
            else:
                return res


class MLPF(nn.Module):
    def __init__(self, config=None, **kwargs):
        super(MLPF, self).__init__()

        if config is None:
            # Backward compatibility or manual construction
            from mlpf.standalone.dsl import i, h, g, s, f, o, ModelConfig

            input_dim = kwargs.get("input_dim", 55)
            embedding_dim = kwargs.get("embedding_dim", 128)
            width = kwargs.get("width", 128)
            num_convs = kwargs.get("num_convs", 6)
            num_heads = kwargs.get("num_heads", 16)
            attention_type = kwargs.get("attention_type", "global")

            if attention_type == "hept":
                layer = h(num_heads, embedding_dim, width * 4)
            elif attention_type == "standard":
                layer = s(num_heads, embedding_dim, width * 4)
            elif attention_type == "fastformer":
                layer = f(num_heads, embedding_dim, width * 4)
            else:
                layer = g(num_heads, embedding_dim, width * 4)

            config = ModelConfig(
                input=i(input_dim, embedding_dim, width * 2),
                backbone={"shared": layer * num_convs},
                output=o(kwargs.get("num_classes", 8), width * 2),
            )

        self.config = config
        self.elemtypes = [1, 2, 3, 4, 5, 8, 9, 10, 11]

        # 1. Input encoding
        if config.input.type == "default":
            self.nn0 = ffn(config.input.input_dim, config.input.embedding_dim, config.input.width, dropout=config.input.dropout)
            self.type_emb = nn.Embedding(12, config.input.embedding_dim)
        elif config.input.type == "projection_only":
            self.nn0 = nn.Linear(config.input.input_dim, config.input.embedding_dim)
        elif config.input.type == "advanced":
            self.nn0 = ffn(config.input.input_dim, config.input.embedding_dim, config.input.width, dropout=config.input.dropout)
            self.type_emb = nn.Embedding(12, config.input.embedding_dim)
            self.coord_proj = nn.Linear(2, config.input.embedding_dim)

        # 2. Backbone
        self.backbone = nn.ModuleDict()
        for k, layers in config.backbone.items():
            self.backbone[k] = nn.ModuleList()
            for layer_cfg in layers:
                layer_class = SUPPORTED_ATTENTION_LAYERS[layer_cfg.type]
                self.backbone[k].append(layer_class(**layer_cfg.__dict__))

        # 3. Output heads
        decoding_dim = config.input.embedding_dim
        self.nn_id = ffn(decoding_dim, config.output.num_classes, config.output.width, dropout=config.output.dropout)

        rg_mode = config.output.rg_mode
        self.reg_heads = nn.ModuleDict()
        for feat in ["pt", "eta", "sin_phi", "cos_phi", "energy"]:
            mode = rg_mode[feat] if isinstance(rg_mode, dict) else rg_mode
            self.reg_heads[feat] = RegressionOutput(mode, decoding_dim, config.output.width, self.elemtypes, dropout=config.output.dropout)

    def forward(self, X, mask, return_attn=False):
        # X: [B, N, 55]
        # mask: [B, N]
        if mask is not None:
            mask_ = mask.unsqueeze(-1)

        # 1. Encoding
        if self.config.input.type == "default":
            x = self.nn0(X)
            x = x + self.type_emb(X[..., 0].long())
        elif self.config.input.type == "projection_only":
            x = self.nn0(X)
        elif self.config.input.type == "advanced":
            x = self.nn0(X)
            x = x + self.type_emb(X[..., 0].long())
            eta_phi = X[..., 2:4]
            x = x + self.coord_proj(eta_phi)

        if mask is not None:
            x = x * mask_

        # 2. Backbone
        attns = []
        if "shared" in self.backbone:
            for layer in self.backbone["shared"]:
                if return_attn:
                    x, attn = layer(x, mask, X, return_attn=True)
                    attns.append(attn)
                else:
                    x = layer(x, mask, X)

        # 3. Output
        # PID
        x_id = x
        if "pid" in self.backbone:
            for layer in self.backbone["pid"]:
                x_id = layer(x_id, mask, X)
        preds_id = self.nn_id(x_id)

        # Regression
        x_reg = x
        if "reg" in self.backbone:
            for layer in self.backbone["reg"]:
                x_reg = layer(x_reg, mask, X)

        preds_pt = self.reg_heads["pt"](X, x_reg, X[..., 1:2])
        preds_eta = self.reg_heads["eta"](X, x_reg, X[..., 2:3])
        preds_sin_phi = self.reg_heads["sin_phi"](X, x_reg, X[..., 3:4])
        preds_cos_phi = self.reg_heads["cos_phi"](X, x_reg, X[..., 4:5])
        preds_energy = self.reg_heads["energy"](X, x_reg, X[..., 5:6])

        preds_momentum = torch.cat([preds_pt, preds_eta, preds_sin_phi, preds_cos_phi, preds_energy], dim=-1)

        # Placeholder for binary particle prediction (legacy)
        preds_binary = torch.zeros((x.shape[0], x.shape[1], 2), device=x.device)

        if return_attn:
            return preds_binary, preds_id, preds_momentum, attns
        return preds_binary, preds_id, preds_momentum, None


def train(model, loader, optimizer, device):
    model.train()
    total_loss = 0
    for i, batch in enumerate(loader):
        X = batch.X.to(device)
        y = batch.y.to(device)
        mask = batch.mask.to(device)

        optimizer.zero_grad()
        _, preds_id, preds_momentum, _ = model(X, mask)

        # Simple cross-entropy for PID
        # preds_id: [B, N, num_classes]
        # target_id: y[:, :, 0]
        loss_id = F.cross_entropy(preds_id.reshape(-1, preds_id.shape[-1]), y[:, :, 0].long().reshape(-1), reduction="none")
        loss_id = (loss_id * mask.reshape(-1)).sum() / mask.sum()

        # Simple MSE for momentum
        # preds_momentum: [B, N, 5]
        # target_momentum: y[:, :, 2:7]
        loss_reg = F.mse_loss(preds_momentum, y[:, :, 2:7], reduction="none")
        loss_reg = (loss_reg.sum(dim=-1) * mask).sum() / mask.sum()

        loss = loss_id + loss_reg
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        if i % 10 == 0:
            print(f"  Step {i}, Loss: {loss.item():.4f} (ID: {loss_id.item():.4f}, Reg: {loss_reg.item():.4f})")

    return total_loss / len(loader)


@torch.no_grad()
def validate(model, loader, device):
    model.eval()
    total_loss = 0
    for batch in loader:
        X = batch.X.to(device)
        y = batch.y.to(device)
        mask = batch.mask.to(device)

        _, preds_id, preds_momentum, _ = model(X, mask)

        loss_id = F.cross_entropy(preds_id.reshape(-1, preds_id.shape[-1]), y[:, :, 0].long().reshape(-1), reduction="none")
        loss_id = (loss_id * mask.reshape(-1)).sum() / mask.sum()

        loss_reg = F.mse_loss(preds_momentum, y[:, :, 2:7], reduction="none")
        loss_reg = (loss_reg.sum(dim=-1) * mask).sum() / mask.sum()

        total_loss += (loss_id + loss_reg).item()

    return total_loss / len(loader)
